name: Build Web

on:
  pull_request:
    branches:
      - src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.24.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --release
    
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./build/web
        publish_branch: main

