name: Build Web

on:
  pull_request:
    branches:
      - src

jobs:
  env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check Java version
        run: java -version
  

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Build Apk
        run: flutter build apk
        
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web
          publish_branch: main
          
      # - name: Deploy to Server
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/aws.pem
      #     chmod 600 ~/.ssh/id_rsa
      #     rsync -avz -e "ssh -i ~/.ssh/aws.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p " build/web/ ec2-user@$3.112.253.1:/home/ec2-user/deploy/home/